//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            image_link = "~/Content/images/upload-i.jpg";
            this.ORDERs = new HashSet<ORDER>();
        }
        public int product_id { get; set; }
        public int catalog_id { get; set; }
        public string product_name { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> product_status { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> vat { get; set; }
        public string description { get; set; }
        public string image_list { get; set; }
        public string image_link { get; set; }
        public Nullable<int> price_out { get; set; }
        public Nullable<int> price_in { get; set; }
    
        public virtual CATALOG CATALOG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
