//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class SLIDE
    {
        public SLIDE()
        {
            image = "~/Content/images/upload-i.jpg";
        }
        public int slide_id { get; set; }
        public string image { get; set; }
        public Nullable<int> slide_order { get; set; }
        public string link { get; set; }
        public string description { get; set; }

        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
