//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoDB2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACTION()
        {
            this.ORDERs = new HashSet<ORDER>();
        }
    
        public int transaction_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> transaction_status { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_phone { get; set; }
        public string user_address { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> payment { get; set; }
        public string payment_info { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> transaction_created { get; set; }
        public string security { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER> ORDERs { get; set; }
        public virtual USER USER { get; set; }
        public List<TRANSACTION> ListTransactionStatus { get; set; }
    }
}
