//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoGiaDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATALOG()
        {
            this.NEWs = new HashSet<NEW>();
            this.PRODUCTs = new HashSet<PRODUCT>();
        }
    
        public int catalog_id { get; set; }
        public string catalog_name { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> sort_order { get; set; }
        public string description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NEW> NEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT> PRODUCTs { get; set; }
        public List<CATALOG> ListCata { get; set; }
    }
}
