//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoGiaDung.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int order_id { get; set; }
        public int transaction_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> amout { get; set; }
        public string data { get; set; }
        public Nullable<int> order_status { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual TRANSACTION TRANSACTION { get; set; }
    }
}
